### ISSUE TITLE
No "Create or Connect your ORCID iD" Link

### ISSUE THREAD

**Issue by dennmuel** [eprints/orcid_support_advance#1]
Hi everyone,

as stated in this [doc](https://wiki.eprints.org/w/ORCID_Support#Connecting_to_orcid.org), we expected to see a link labeled "Create or Connect your ORCID iD" for users, that do not have an orcid. However, this link does not show up.

Furthermore it is now no more possible to add an orcid to a user profile manually. The respective field just doesn't take any input. Same goes for the fields in the workflow.

We have have registered as a trusted application in the sandbox and filled out the client-id and -secret in `z_orcid_support_advance.pl`.

Could you please help us find out what we're missing to do?
Many thanks in advance!

**Comment by zuphilip** [comment]
It looks the ORCID fields for the creators of an entry are now read-only (autocompleting does still work there).

**Comment by dennmuel** [comment]
Saw that, too, but wasn't sure if that is intended or not.

**Comment by wfyson** [comment]
Just to clarify, the ORCID fields are read-only by design as this was a requirement set out by orcig.org - user's are never expected to manually type in their ORCID.

**Comment by wfyson** [comment]
As for why the 'Create or Connect your ORCID iD" link is not appearing, I'm afraid I've not come across this issue myself. The link should appear as long as you are logged in and the plugin is set to appear in 'key_tools'. If you have any config at a more local level that may be overwriting how key_tools is displayed then this might be causing the issue (e.g. I believe dynamic_template.pl can sometimes affect this).

**Comment by dennmuel** [comment]
Hello @wfyson ,
thanks for your reply. I'll follow your suggestion and come back to you later. (Might take until may because of a vacation.) Also I'll double-check permissions and the like again, just to be sure I hadn't missed something.
Best regards

**Comment by dennmuel** [comment]
Hello again,
we seem to have solved the problem by reinstalling and double-checking the permissions. Looks like the first installation wasn't done properly due to stupidity on my part. I'm really sorry for stealing your time.
Best regards

**Comment by wfyson** [comment]
No worries - glad to hear you got it sorted and please do raise any other issues you come across. The plugin is still under development so may well require some future tweaking.

**Comment by zuphilip** [comment]
> Just to clarify, the ORCID fields are read-only by design as this was a requirement set out by orcig.org - user's are never expected to manually type in their ORCID.

@wfyson But how can then an electronic dissertation in EPrints deposited with the metadata such that it will be exported to the user's ORCID profile as well?
