### ISSUE TITLE
WP4: Improved UX of import/export screens

### ISSUE THREAD

**Issue by wfyson** [eprints/orcid_support_advance#14]
Messages displayed following actions of the import/export screens should display more accurate information, e.g. if one record is successfully exported and one isn't, an appropriate message should be displayed.

Additional “Select all/Deselect all” options.

**Comment by zuphilip** [comment]
We have implemented a "Select all/Deselect all" and a last-modfied-date filter, which currently looks like this:

![madoc-export-orcid-ui](https://user-images.githubusercontent.com/5199995/44548092-64b0d200-a71d-11e8-80c4-8a8fb694636f.png)

**Comment by zuphilip** [comment]
The first part of this issue is also related to #6.

**Comment by dennmuel** [comment]
We're kind of working on this in our instance. Gonna get back to this issue with a PR when we're ready.
Also related to #12.

**Comment by wfyson** [comment]
These updates are now available in v1.5 of the plugin: http://bazaar.eprints.org/1102/

Many thanks @dennmuel and @zuphilip !
