### ISSUE TITLE
WP8: Export affiliation start date

### ISSUE THREAD

**Issue by wfyson** [eprints/orcid_support_advance#18]
When adding an affiliation to orcid.org profile include a start date will be required. EPrints does not store this by default, so use user creation date by default.

**Comment by dennmuel** [comment]
If desired we could also provide a small code snippet to add the user's department to the affiliation.
(By simply reading it via `$user->get_value( "dept" )`)

**Comment by wfyson** [comment]
At present the plugin doesn't add employment if the institution's record is already in the ORCID profile - rather than not add employment  in these instances, we should look into adding the repository as the preferred source of this information instead.

**Comment by cziaarm** [comment]
According to Paula from ORCID affiliation start date will *not* be mandatory for api v3.0 :)
