### ISSUE TITLE
Import hash ref error

### ISSUE THREAD

**Issue by dennmuel** [eprints/orcid_support_advance#2]
Hello @wfyson ,

yes, it's me again ;) We are testing the plugin with the orcid sandbox api at the moment and I came across an error when trying to import from orcid (for instance via the button above the user profile or in "manage deposits").

The browser gives me a `500 internal server` error while the apache log says
`Can't use string ("Ursachen und Konsequenzen ambiva"...) as a HASH ref while "strict refs" in use at /usr/share/eprints3/perl_lib/EPrints/MetaField/Compound.pm line 391.\`
where "Ursachen und Konsequenzen ambiva" is the beginning of the first title that should be imported from orcid.

It doesn't seem to be related to that specific record: When I unselect it the same error occurs for the next record in row.

Do you have any experience/thoughts/tips on this? Please let me know, if I can provide further information.

Best regards
Dennis

**Comment by zuphilip** [comment]
Is our data structure for the title field following the default? I remember that there where some different cases (for title in several languages, thus possibly multiple values?):
* $publication['title']
* $publication['title']['title']
* $publication['title']['item']['name']

Cf. https://github.com/UB-Mannheim/publist4ubma2/blob/e186c8e198a4a8e71c8dfb02881dd181691cefb9/Classes/Controller/PublicationController.php#L164-L169

**Comment by dennmuel** [comment]
Looks like you're right. Matching the orcid title to our eprints `title_title` field gets rid of the error.
