### ISSUE TITLE
German locale not updated in bazaar package

### ISSUE THREAD

**Issue by dennmuel** [eprints/orcid_support_advance#32]
Hi,
it looks like the German static/orcid_support_advance.xpage and phrases/z_orcid_support_advance.xml have not been updated with the [last bazaar release](http://bazaar.eprints.org/1102/).

Please have a look, if I'm mistaken.

Best regards
Dennis

**Comment by wfyson** [comment]
Hi @dennmuel - sorry about that, I'll make sure they're included in the next release.

**Comment by dennmuel** [comment]
No problem, I only saw that by chance and wasn't sure what to make of it.

Best regards
Dennis
