### ISSUE TITLE
Trusted organization not unset on ORCID profile when user disconnects

### ISSUE THREAD

**Issue by drn05r** [eprints/orcid_support_advance#58]
Raised by Ranju Upadhyay on EPrints-Tech mailing list:

We are testing ORCID integration in eprints. we have installed all the plugins and most of the things seem to work. However, there is one part that does not seem to work as ORCID expects it to. When a user disconnects from ORCID in her/his profile in eprints, the "Trusted Organisation" section in ORCID side does not get updated i.e it does not delete the Trusted Organisation from users profile in ORCID even though the user has disconnected . 

ORCID says it should.

**Comment by wfyson** [comment]
Fixed with commit https://github.com/eprints/orcid_support_advance/commit/22229b748482301be249ba5316b8ee3a9e16e988
