### ISSUE TITLE
ISNI not supported by ORCID for organization disambiguation

### ISSUE THREAD

**Issue by drn05r** [eprints/orcid_support_advance#60]
I was told by the ORCID support team that ISNI is not properly supported for organization disambiguation.  As RINGGOLD requires a paid for account to do organization ID lookups, we should provide advice as a configuration comment on what should be used as an alternative to RINGGOLD.  

I think GRID is the best option, as it has a straightforward and [free lookup service](https://www.grid.ac/institutes) and ORCID list it as a [supported organization ID provider](https://info.orcid.org/documentation/integration-guide/working-with-organization-identifiers/).  We should update the comment to recommend GRID at least as an alternative with its lookup URL.

**Comment by wfyson** [comment]
Updated to GRID with commit https://github.com/eprints/orcid_support_advance/commit/6405d7bf329c2e17502c5a58a23be0399fa83574
