### ISSUE TITLE
Retrieve read limited information from your ORCID record

### ISSUE THREAD

**Issue by photomedia** [eprints/orcid_support_advance#61]
This line "Retrieve read limited information from your ORCID record" is intended to be understandable by the human user:
https://github.com/eprints/orcid_support_advance/blob/22229b748482301be249ba5316b8ee3a9e16e988/lib/lang/en/static/orcid_support_advance.xpage#L35
However, the grammar is really difficult to follow.  Should it be "Retrieve read-limited information from your ORCID record"?  That's still confusing, as most people will not understand the term "read-limited information", but at least the hyphen makes it a little clearer?  Is there a definition of "read-limited information" that we could link to?
Is this the same permission that is referred to here?
https://support.orcid.org/hc/en-us/articles/360006897614-Visibility-settings
"Trusted organizations: The organization will ask you to grant them specific permission to _read limited-access information_ at the same time that you give them permission to get your ORCID iD."?  In that case, should we use the same term "limited-access information"?

**Comment by wfyson** [comment]
Hi @photomedia, thanks for the suggestion of making this page a bit clearer. I've updated it to reflect the text of the actual Manage ORCID Permissions page which I think is clearer and helps keeps things more consistent. I've also added a bit extra to reflect that the latest updates allow you to auto-export now too as a separate permission: https://github.com/eprints/orcid_support_advance/commit/279c02575751a0971282cacd50148a5974707e83
