### ISSUE TITLE
Clarify on export interface that Only items with an ORCID in the metadata will appear as options for export

### ISSUE THREAD

**Issue by photomedia** [eprints/orcid_support_advance#62]
It is possible to have many items in a repository with an author name, but no ORCID.  A user may be very confused why these items are not showing up as "Export" options to ORCID.  Should we include a message/info somewhere to clarify that "Only items with an ORCID in the metadata will appear as options for export"?  This means that a user might have to manually edit their author metadata to ensure that the ORCID is included before it can appear as an export option to ORCID.

**Comment by wfyson** [comment]
Hi @photomedia, I've added a new intro phrase to both the export and import screens (for consistency). Hope this helps!

**Comment by photomedia** [comment]
Yes, thank you, this helps!  I was able to add the phrase "Only items with your ORCID listed as a contributor are available for export." to the export screen.
